### ISSUE TITLE
suggest a few header style

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/attendbos-web#23]
![image](https://user-images.githubusercontent.com/30463117/230263111-f81b9f0e-ef43-43a8-b6f0-bb88577991c7.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (539)](https://user-images.githubusercontent.com/74038076/230288716-f57c0493-7ae0-45bd-8642-122be4105890.png)
![Screenshot (545)](https://user-images.githubusercontent.com/74038076/230288757-d180e7bc-e9c1-4bae-953c-04b8dc3a8ab2.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (550)](https://user-images.githubusercontent.com/74038076/230288850-383fc7a0-2080-4345-9402-51fadaa1d628.png)
![Screenshot (551)](https://user-images.githubusercontent.com/74038076/230288860-bbeeec79-45e9-4bb2-9ad5-2591fa9281fe.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (541)](https://user-images.githubusercontent.com/74038076/230288961-3dd40257-571b-4fc9-add5-4f8ed86c4c78.png)
![Screenshot (547)](https://user-images.githubusercontent.com/74038076/230288974-557f784f-45c6-4e51-aa12-eb49ae38b348.png)
![Screenshot (542)](https://user-images.githubusercontent.com/74038076/230289024-ee9ec822-fef3-4ffe-ae63-f15d0ea1cc20.png)
![Screenshot (548)](https://user-images.githubusercontent.com/74038076/230289047-ff355482-c549-402c-a8d1-1e91de4033a9.png)
![Screenshot (540)](https://user-images.githubusercontent.com/74038076/230289063-8c22c2d1-582b-4254-8f83-d43275fc065b.png)
![Screenshot (546)](https://user-images.githubusercontent.com/74038076/230289075-3e569ed2-8417-49e4-8e86-451661f12126.png)

**Comment by rosclaritha** [comment]
@NadhirahIzzati please provide more suggestions. can also change the background.

**Comment by NadhirahIzzati** [comment]
![Screenshot (556)](https://user-images.githubusercontent.com/74038076/230845104-75f95ecc-9241-4ddd-834a-352463a3a2ea.png)
![Screenshot (560)](https://user-images.githubusercontent.com/74038076/230845135-6882436e-51cd-4bbc-9a3e-af382bf546f7.png)
![Screenshot (561)](https://user-images.githubusercontent.com/74038076/230845158-6ffbe4e6-19bf-4f32-806e-cf1fcb70f82d.png)
![Screenshot (562)](https://user-images.githubusercontent.com/74038076/230845273-3e238ce7-323b-4981-af9c-d0224195dc6c.png)
![Screenshot (564)](https://user-images.githubusercontent.com/74038076/230845298-6bb4531d-a9fa-4c72-94c8-7fd703f2ce0c.png)

**Comment by rosclaritha** [comment]
Title: Streamline Attendance Tracking
Description: Your Solution for Efficient Workforce Management

Design something like this:
![image](https://user-images.githubusercontent.com/30463117/232976287-8b0a20cd-fff0-4ca8-bd35-338d81c5944c.png)
