### ISSUE TITLE
change problem design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/attendbos-web#32]
- [x] suggest a few design
![image](https://user-images.githubusercontent.com/30463117/234766375-2c4cd038-3899-4142-8e15-9aa26fb90367.png)

**Comment by NadhirahIzzati** [comment]
![design-8](https://user-images.githubusercontent.com/74038076/235043966-a954dda5-52f6-46ae-87b0-c701786797ec.png)
![design-7](https://user-images.githubusercontent.com/74038076/235043976-a11a0971-3a73-4a57-8c23-ccf7054cdcfa.jpg)

![design-9](https://user-images.githubusercontent.com/74038076/235044005-b64eb188-f3b1-4de7-9732-63de73cd7e78.png)


![Screenshot (659)](https://user-images.githubusercontent.com/74038076/235044047-f5fd4fcb-6684-402c-8273-02745bb4825a.png)

![Screenshot (657)](https://user-images.githubusercontent.com/74038076/235044057-38c3797e-3ddc-4e9d-a28c-033f30804e11.png)
![Screenshot (656)](https://user-images.githubusercontent.com/74038076/235044081-7ca09ba2-7a64-41a8-8f7f-f01c0261f1cd.png)
![design-6](https://user-images.githubusercontent.com/74038076/235044202-a3a417f7-4c7b-4a72-bcc5-3f3287689066.png)

![Screenshot (660)](https://user-images.githubusercontent.com/74038076/235044285-00712109-7113-4b41-97e6-7d4f9c7c34ff.png)

**Comment by rosclaritha** [comment]
@NadhirahIzzati 
![image](https://user-images.githubusercontent.com/30463117/235046020-7e9a0e05-2678-49ed-b433-563fe7c838e5.png)

move the cta in between feature & solution
![image](https://user-images.githubusercontent.com/30463117/235046102-f84d76d7-d2c7-4e88-9c81-e99929599418.png)
