### ISSUE TITLE
update solution design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/attendbos-web#36]
- [x] suggest design
- [x] update the code after design has been selected

![image](https://user-images.githubusercontent.com/30463117/235569122-e7256f02-3476-4427-ba3e-83ff307bdbae.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (664)](https://user-images.githubusercontent.com/74038076/235861188-4cc5a1ce-0c4e-47d2-b258-8aee3d3b540e.png)
![Screenshot (665)](https://user-images.githubusercontent.com/74038076/235861197-326ffee9-f4d1-492c-87ff-776a00104062.png)
![Screenshot (666)](https://user-images.githubusercontent.com/74038076/235861220-e4e71c95-5821-4bf7-bb13-2bb2a7254432.png)

![Screenshot (667)](https://user-images.githubusercontent.com/74038076/235861284-cc1eb6ac-6b5d-40ad-b8c7-5cba1c9bfd72.png)
![Screenshot (668)](https://user-images.githubusercontent.com/74038076/235861298-587477bd-9107-4748-8674-3dbeac61b6ac.png)

![Screenshot (677)](https://user-images.githubusercontent.com/74038076/235861322-0e69c31a-90b8-4cd6-a0ec-3b594b395736.png)
![Screenshot (678)](https://user-images.githubusercontent.com/74038076/235861671-d6589735-dd43-48b7-b9bd-274723c29cd4.png)

![Screenshot (679)](https://user-images.githubusercontent.com/74038076/235861348-20e2ba27-cdbe-4ddb-adcb-fa828a5f69be.png)

![Screenshot (681)](https://user-images.githubusercontent.com/74038076/235861376-d4d8d975-ec17-4625-a25d-d757b3bcee78.png)
![Screenshot (682)](https://user-images.githubusercontent.com/74038076/235861409-bb1192f4-989e-4c9f-970a-11c7f27dd09f.png)


![Screenshot (680)](https://user-images.githubusercontent.com/74038076/235861365-7acb48e3-ffe5-4630-826b-ce370e994d51.png)
![Screenshot (683)](https://user-images.githubusercontent.com/74038076/235861420-9edfdce9-8eb4-4418-b337-7879c8d1145c.png)

**Comment by rosclaritha** [comment]
use something like this @NadhirahIzzati 
![image](https://user-images.githubusercontent.com/30463117/236384422-b66c1c9f-514a-4625-801e-528afc8d5176.png)
